completed week 2 assessments, did not complete stretch goal due to fe…
learn-academy-2023-bravo/week-2-assessment-Bjohnwell pull request #1
Opened 2023-03-27 03:42 UTC by Bjohnwell

…eling unwell

# Submitting Week 2 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ x] Coding Challenges
- [x ] Coding Concepts
- [x ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-03-28 03:09 UTC, Genemichael25 requested changes
Brandon this is a very solid start to this assessment, but I am requesting changes for the following: 1. Need a researched answer in your words for # 3 and 4 in interview questions. 2. Missing answer and explanation for coding concepts # 3. I understand you weren't feeling well and I appreciate the work you did, it looks really good. Let's finish it off strong, make those small changes, push up on the same branch, and then notify me so I can finish reviewing. Thanks

2023-03-28 03:09 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain: ['B', 'r', 'a', 'v','o', ' ', '2', '0','2', '3'] .split will break apart the the characters in a string and will return an arrary of the characters in the string. Where i mi
Great follow up!

2023-03-28 03:09 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain: (name) is not defined anywhere withing our function. It is essentially acting a place holder to make the function dynamic so we can pass in any variable that we have already
Nice job realizing name is a placeholder. It is a parameter that like you mentioned, we can then pass any data we want. The reason we get undefined here is because there is no return.

2023-03-28 03:09 UTC, Genemichael25 commented on coding-concepts.js
Missing answer here.

2023-03-28 03:09 UTC, Genemichael25 commented on interview-questions.md
> +Parameters are linked to the function arguments in that they must be the same data type.
This is awesome! Love the example and then your interpretation on the researched answer! 💯

2023-03-28 03:09 UTC, Genemichael25 commented on interview-questions.md
And your interpretation?

2023-03-30 16:35 UTC, Bjohnwell commented on coding-concepts.js
Completed this

2023-03-30 16:35 UTC, Bjohnwell commented on interview-questions.md
resolved this

2023-03-30 21:43 UTC, Genemichael25 approved these changes
Overall, great work on this one Brandon! The pseudocode and functions look amazing and you seem to have a strong understanding of the concepts so far. This displays an Advanced Beginner level of comprehension and you are on the right path. I appreciate the test messages you leave on there and how you break it down into red-green-refactor! Continue to expand on the interview questions to help you get to that next level but you are well on your way there. 👏🏽

2023-03-30 21:43 UTC, Genemichael25 commented on code-challenges.test.js
> +
Great job here with the pseudocode and function!

2023-03-30 21:43 UTC, Genemichael25 commented on code-challenges.test.js
> +describe("capitalNouns", () => {
Keep setting up your tests like this! 💯

2023-03-31 20:03 UTC, merged